name: Packer and Terraform CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "us-west-2"

      # Step 3: Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.0"  # Specify the Terraform version you want

      # Step 4: Install Packer
      - name: Install Packer
        run: |
          curl -LO https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip packer_1.8.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      # Step 5: Run Packer to build the AMI
      - name: Build AMI with Packer
        run: packer build packer.json

      # Step 6: Extract the AMI ID from the Packer build (this can be parsed from the output or manifest)
      - name: Extract AMI ID
        id: ami_id
        run: |
          AMI_ID=$(jq -r '.builds[0].artifact_id' packer-manifest.json | sed 's/.*ami-/ami-/')
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      # Step 7: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init
      # Step 8: Validate Terraform
      - name: Validate Terraform
        run: terraform validate
      # Step 9: Plan Terraform
      - name: Plan Terraform
        run: terraform plan

      # Step 10: Apply Terraform configuration
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve -var="ami_id=${{ env.AMI_ID }}"
